kubernetesType: Openshift  #Vanilla for community kubernetes distribution else Openshift for Openshift

## In case of using these charts on Openshift then please use UBI images
## To know more about them follow this tutorial https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed/-/tree/master/openshift
nfimage:   # image name either locally present or in a public/private repository
  #repository: image-registry.openshift-image-registry.svc:5000/oaicicd-ran/oai-flexric  ## dockerhub oaisoftwarealliance/oai-gnb  
  repository: image-registry.openshift-image-registry.svc:5000/oaicicd-core/oai-flexric
  version:  develop-891599d3 # image tag or develop
  # pullPolicy: IfNotPresent or Never or Always
  pullPolicy: IfNotPresent

## good to use when pulling images from docker-hub mention 
#imagePullSecrets: 
#  - name: "regcred"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "oai-flexric-sa"

## CU-CP can work with 1 virtual ip-address here we are using three different virtual interfaces. 
## In case you are using 1 ip-address for all 3 logical interfaces then please change it template/configmap.yaml
## Change these ip-addresses according to your environment

multus:
  # to remove the default gateway change it with ""
  defaultGateway: "172.21.7.254"
  e2Interface:
    create: true
    IPadd: "172.21.6.198"
    Netmask: "22"
    # #name inside the pod is hardcoded right now
    # name: "e1"
    # if gatway is empty then it will be removed
    #Gateway: ""
    #routes: [{'dst': '10.8.0.0/24','gw': '172.21.7.254'}, {'dst': '10.9.0.0/24','gw': '172.21.7.254'}]
    hostInterface: "br-ex"      # Interface of the host machine on which this pod will be scheduled

## configuration file is in template/config.yaml 
## It is taken from https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/ci-scripts/conf_files/gnb-cucp.sa.f1.conf
config:
  timeZone: "Europe/Paris"

# Debugging section
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

start:
  ric: start
  tcpdump: false

includeTcpDumpContainer: false #If true it will add a tcpdump container inside network function pod for debugging

## For openshift you can use rhel8/support-tools:8.7-13
tcpdumpimage:
   repository: docker.io/corfr/tcpdump
   version: latest
   #pullPolicy: IfNotPresent or Never or Always
   pullPolicy: IfNotPresent

## NF is the network function and tcpdump is the tcpdump container. 
## To know more about request and limit it is better to understand that how Kubernetes QoS works. 
## https://kubernetes.io/docs/concepts/configuration/manage-resources-containers
## https://kubernetes.io/docs/concepts/workloads/pods/pod-qos
resources:
  define: true
  limits:
    nf:
      cpu: 500m
      memory: 512Mi
    #If tcpdump container is disabled this value will not be used
    tcpdump:
      cpu: 100m
      memory: 128Mi
  requests:
    nf:
      cpu: 500m
      memory: 512Mi
    #If tcpdump container is disabled this value will not be used
    tcpdump:
      cpu: 100m
      memory: 128Mi


tolerations: []

affinity: {}

terminationGracePeriodSeconds: 5

nodeSelector:
  worker: "telcort"

nodeName: 
