version: '3.8'
services:
    gnb-emu:
        container_name: "gnb-emu"
        image: phinetech/cn5g-tester:latest
        environment:
            - TZ=Europe/Paris
        command:
            - /bin/bash
            - -c
            - |
                # ./eth-pdu.py --gnb_ip=192.168.70.143 --gtp_ip=192.168.71.143 --amf_ip=192.168.70.132
                tail -f /dev/null
        networks:
            public_net:
                ipv4_address: 192.168.70.143
            n3_net:
                ipv4_address: 192.168.71.143

networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    n3_net:
        driver: bridge
        name: demo-oai-n3-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-n3"