version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:2024.w36
        privileged: true
        container_name: oai-gnb
        environment:
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
        volumes:
            - ./ran-conf/gnb_ebpf.conf:/opt/oai-gnb/etc/gnb.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.153
            n3_net:
                ipv4_address: 192.168.71.153
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue1:
        image: oaisoftwarealliance/oai-nr-ue:2024.w36
        privileged: true
        container_name: oai-nr-ue1
        environment: 
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --rfsimulator.serveraddr 192.168.70.153 --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nr-ue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.154
            n3_net:
                ipv4_address: 192.168.71.154
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue2:
        image: oaisoftwarealliance/oai-nr-ue:2024.w26
        privileged: true
        container_name: oai-nr-ue2
        environment:
            USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 001010000000101 -C 3619200000 --rfsimulator.serveraddr 192.168.70.153 --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nr-ue2.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.155
            n3_net:
                ipv4_address: 192.168.71.155
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
    n3_net:
        external:
            name: demo-oai-n3-net

