kubernetesType: Openshift  #Vanilla for community kubernetes distribution

nfimage:
  repository: image-registry.openshift-image-registry.svc:5000/oaicicd-core/oai-udm #docker.io/oaisoftwarealliance/oai-udm         
  version: UDM_TAG                        #image tag, develop tag for experimental features 
  #pullPolicy: IfNotPresent or Never or Always
  pullPolicy: IfNotPresent

tcpdumpimage:
  repository: image-registry.openshift-image-registry.svc:5000/oaicicd-core/oai-traffic-gen
  version: latest
  #pullPolicy: IfNotPresent or Never or Always
  pullPolicy: Always

initContainer:
  repository: image-registry.openshift-image-registry.svc:5000/oaicicd-core/oai-init
  version: latest
  #pullPolicy: IfNotPresent or Never or Always
  pullPolicy: IfNotPresent


## good to use when pulling images from docker-hub mention 
#imagePullSecrets: 
#  - name: "regcred"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "oai-udm-sa"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

#service type is fixed to clusterIP, it is only support for non multus interface (eth0)

securityContext:
  capabilities:
    add:
     - NET_ADMIN
    drop:
     - ALL
  privileged: true

start:
  udm: true
  tcpdump: true

config:
  tz: "Europe/Paris"
  nrfFqdn: "oai-nrf"
  sbiPortHttp1: 80
  sbiPortHttp2: 8080

persistent:
  sharedvolume: true
  volumeName: nfs-client
  size: 1Gi

resources:
  define: true
  limits:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    nf:
      cpu: 200m
      memory: 512Mi
  requests:
    tcpdump:
      cpu: 100m
      memory: 128Mi
    nf:
      cpu: 200m
      memory: 512Mi

readinessProbe: true

livenessProbe: false

terminationGracePeriodSeconds: 5

nodeSelector: {}

nodeName:
