apiVersion: v1
kind: Service
metadata:
  name: oai-flexric
  labels:
    app: oai-flexric
    {{- include "oai-flexric.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: e2
      port: 36421
      targetPort: 36421
      protocol: SCTP
    - name: e42
      port: 36422
      targetPort: 36422
      protocol: SCTP
  selector:
    {{- include "oai-flexric.selectorLabels" . | nindent 4 }}
